### ISSUE TITLE
Link to the blog posts as you write them

### ISSUE THREAD

**Issue by cloudbring** [sevenseacat/ticketee-phoenix#1]
As you write this app and blog about it (example: http://sevenseacat.net/2015/06/01/custom_page_titles_in_phoenix.html) you should link to the series of blog posts.

**Comment by sevenseacat** [comment]
That's a great idea, and if I write more blog posts, I'll do it!

For now I've pushed my changes about setting page titles, and linked to the blog post in the commit message, if anyone is so inclined to read it :)
